# Skip the Dishes Hackathon

### Team 3: Conway, Patrick, Marina, Katherine, Mesbah, Aref

In [1]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

This notebook is for reviewing the data on SkipTheDishes.

In [2]:
df_supply = pd.read_csv('~/Downloads/FoodSupplyandDisposition_CA_1960-2018.csv')

In [3]:
df_supply

,REF_DATE,Commodity,UOM,Beginning stocks,Domestic disappearance,Ending stocks,Exports,Imports,Manufacturing,Production,Total disposition,Total supply,Waste
0,1960,"Ale, beer, stout and porter",Kilolitres,NaN,1070.44,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN
1,1960,Apple juice,Tonnes,28.57,38.54,22.49,1.29,NaN,NaN,33.75,23.78,62.32,NaN
2,1960,Apple sauce,Tonnes,6.37,6.70,4.67,NaN,NaN,NaN,5.00,6.70,11.37,NaN
3,1960,Apples canned,Tonnes,4.33,4.79,4.86,0.41,NaN,NaN,5.73,NaN,10.06,NaN
4,1960,Apples dried,Tonnes,NaN,0.54,NaN,NaN,0.54,NaN,NaN,0.54,0.54,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10985,2018,Wheat flour,Tonnes,33.31,2089.88,28.21,255.73,88.91,87.08,2338.68,2432.69,2460.89,0.00
10986,2018,Whipping cream 32% or 35%,Kilolitres,NaN,59.39,NaN,NaN,NaN,NaN,59.39,59.39,59.39,NaN
10987,2018,Wines,Kilolitres,NaN,530.63,NaN,90.38,415.01,NaN,NaN,621.00,NaN,NaN
10988,2018,Wintermelons fresh,Tonnes,NaN,1.90,NaN,NaN,2.06,NaN,NaN,2.06,2.06,0.17
10989,2018,Yogurt,Kilolitres,NaN,365.70,NaN,9.24,0.55,NaN,374.38,374.94,374.94,NaN

In [4]:
df_supply.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10990 entries, 0 to 10989
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   REF_DATE                10990 non-null  int64
 1   Commodity               10990 non-null  object
 2   UOM                     10990 non-null  object
 3   Beginning stocks        3490 non-null   float64
 4   Domestic disappearance  9307 non-null   float64
 5   Ending stocks           3454 non-null   float64
 6   Exports                 5764 non-null   float64
 7   Imports                 8561 non-null   float64
 8   Manufacturing           2260 non-null   float64
 9   Production              6629 non-null   float64
 10  Total disposition       10723 non-null  float64
 11  Total supply            9589 non-null   float64
 12  Waste                   4034 non-null   float64
dtypes: float64(10), int64(1), object(2)
memory usage: 1.1+ MB

In [5]:
(df_supply.isna().sum()/ df_supply.shape[0]) *100

REF_DATE                   0.000000
Commodity                  0.000000
UOM                        0.000000
Beginning stocks          68.243858
Domestic disappearance    15.313922
Ending stocks             68.571429
Exports                   47.552320
Imports                   22.101911
Manufacturing             79.435851
Production                39.681529
Total disposition          2.429481
Total supply              12.747953
Waste                     63.293904
dtype: float64

In [6]:
df_yelp = pd.read_csv('~/Downloads/Yelp_TO_restaurant_reviews.csv')

In [7]:
df_yelp.sample(5)

,name,address,postal_code,latitude,longitude,stars_x,review_count,is_open,attributes,categories,hours,stars_y,useful,funny,cool,text,date
94327,Marben,488 Wellington Street W,M5V 1E3,43.643594,-79.398503,3.5,258,1,"{'RestaurantsAttire': ""u'casual'"", 'GoodForKid...","American (New), British, Restaurants, Canadian...","{'Monday': '17:0-22:0', 'Tuesday': '17:0-22:0'...",4,1,0,0,LOVE THIS PLACE!\n\ntapas is my favourite styl...,2012-04-02 03:17:54
185781,Rosalinda,133 Richmond Street W,M5H 3A9,43.650077,-79.384831,3.5,81,1,"{'RestaurantsAttire': ""'casual'"", 'Restaurants...","Restaurants, Mexican, Vegan","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'...",5,0,0,0,"WHAT A GREAT PLACE TO EAT ! Service is great ,...",2018-08-23 00:07:50
215253,Carole's Cheesecake Cafe,114 Cumberland Street,M5R 1A6,43.670288,-79.391641,3.5,182,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsPri...","Desserts, Food, Bakeries","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",3,0,0,0,been here couple of times but I guess we quit ...,2014-07-05 04:01:14
93663,Crêpe & Co.,1167 Queen Street W,M6J 1J6,43.642622,-79.425851,3.5,16,0,"{'GoodForKids': 'True', 'GoodForMeal': ""{'dess...","Restaurants, Food, Cafes, Creperies, Coffee & Tea","{'Monday': '7:0-19:0', 'Tuesday': '7:0-19:0', ...",5,1,0,0,I was looking for something to eat for dinner ...,2014-06-25 23:24:51
155297,Donatello Restaurant,37 Elm Street,M5G 1H1,43.657425,-79.383474,4.0,134,1,"{'RestaurantsAttire': ""u'dressy'"", 'BusinessPa...","Italian, Seafood, Restaurants","{'Monday': '16:30-23:0', 'Tuesday': '16:30-23:...",5,0,0,0,I met 6 girl friends here for dinner. One of t...,2016-10-02 17:26:19

In [8]:
df_yelp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 422049 entries, 0 to 422048
Data columns (total 17 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   name          422049 non-null  object
 1   address       421601 non-null  object
 2   postal_code   421749 non-null  object
 3   latitude      422049 non-null  float64
 4   longitude     422049 non-null  float64
 5   stars_x       422049 non-null  float64
 6   review_count  422049 non-null  int64
 7   is_open       422049 non-null  int64
 8   attributes    418953 non-null  object
 9   categories    422049 non-null  object
 10  hours         385287 non-null  object
 11  stars_y       422049 non-null  int64
 12  useful        422049 non-null  int64
 13  funny         422049 non-null  int64
 14  cool          422049 non-null  int64
 15  text          422049 non-null  object
 16  date          422049 non-null  object
dtypes: float64(3), int64(6), object(8)
memory usage: 54.7+ MB

In [9]:
(df_yelp.isna().sum()/ df_yelp.shape[0]) *100

name            0.000000
address         0.106149
postal_code     0.071082
latitude        0.000000
longitude       0.000000
stars_x         0.000000
review_count    0.000000
is_open         0.000000
attributes      0.733564
categories      0.000000
hours           8.710363
stars_y         0.000000
useful          0.000000
funny           0.000000
cool            0.000000
text            0.000000
date            0.000000
dtype: float64

In [10]:
df_yelp = df_yelp.loc[df_yelp['is_open'] == 1]

In [11]:
df_yelp.drop(["hours", "is_open"], axis=1, inplace = True)

In [12]:
df_yelp.reset_index(drop = True, inplace = True)

In [13]:
df_yelp

,name,address,postal_code,latitude,longitude,stars_x,review_count,attributes,categories,stars_y,useful,funny,cool,text,date
0,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",3,1,0,1,Oh? Another patbingsu review? This one was bet...,2017-07-30 23:32:27
1,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",5,2,0,2,What really earns them their 5 stars is the un...,2016-01-31 16:19:16
2,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",4,0,0,0,Located inside the Galleria Supermarket.\nStop...,2016-04-29 03:43:54
3,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",5,0,0,0,Yummy cakes! U should try their sweet potato c...,2017-06-13 23:42:37
4,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",5,10,6,8,One of my favorite bakeries! This bakery is in...,2016-01-26 22:56:47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343228,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",4,1,0,2,I've been here a few times. Almost every time ...,2018-04-17 10:43:30
343229,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",3,0,0,0,I've came here for lunch several times and it ...,2017-11-17 18:12:45
343230,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",3,0,0,0,I feel mean leaving this review because servic...,2018-10-25 02:11:36
343231,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",4,0,0,0,"Decent price for lunch, after tax comes to $10...",2016-06-09 20:42:58
343232,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",5,2,0,0,I've been waiting for a new Thai restaurant in...,2017-05-24 18:40:57

In [14]:
number_of_branches = df_yelp.groupby(by = 'name')['address'].nunique().sort_values(ascending = False)

number_of_branches

name
Starbucks                                 129
Tim Hortons                                94
McDonald's                                 44
Subway                                     43
Pizza Pizza                                33
                                         ...
Choco Churros                               0
Urban Smoke Fusion BBQ Food Truck           0
Beer & Liquor Delivery Service Toronto      0
Culinary Adventure                          0
Per Se Mobile                               0
Name: address, Length: 5241, dtype: int64

In [15]:
df_yelp.loc[df_yelp['name'] == 'Choco Churros']

,name,address,postal_code,latitude,longitude,stars_x,review_count,attributes,categories,stars_y,useful,funny,cool,text,date
271918,Choco Churros,None,NaN,43.653226,-79.383184,3.5,5,"{'RestaurantsPriceRange2': '1', 'BikeParking':...","Food Trucks, Food",4,1,0,1,Great little treat for $5 bucks. I had the tr...,2013-08-16 18:51:39
271919,Choco Churros,None,NaN,43.653226,-79.383184,3.5,5,"{'RestaurantsPriceRange2': '1', 'BikeParking':...","Food Trucks, Food",4,0,0,0,Just tried for the very first time at the food...,2013-08-07 16:12:59
271920,Choco Churros,None,NaN,43.653226,-79.383184,3.5,5,"{'RestaurantsPriceRange2': '1', 'BikeParking':...","Food Trucks, Food",3,0,0,0,Not really much to rave here. It was just ok....,2013-08-21 03:57:50
271921,Choco Churros,None,NaN,43.653226,-79.383184,3.5,5,"{'RestaurantsPriceRange2': '1', 'BikeParking':...","Food Trucks, Food",4,4,1,1,Churros on wheels! Genious! \n\nPlain old ci...,2013-05-14 18:46:26
271922,Choco Churros,None,NaN,43.653226,-79.383184,3.5,5,"{'RestaurantsPriceRange2': '1', 'BikeParking':...","Food Trucks, Food",2,1,1,0,Ordered the same again today. This time they ...,2013-08-09 15:57:17
271923,Choco Churros,None,NaN,43.653226,-79.383184,3.5,5,"{'RestaurantsPriceRange2': '1', 'BikeParking':...","Food Trucks, Food",5,1,0,0,My favourite dessert from my favourite food tr...,2016-03-06 18:24:03

In [16]:
#check other grouping possibilities
df_yelp.groupby(by = ['address','name']).mean()

                                                                       latitude  \
address                                            name
, 200 Bay Street, Unit L5                          Freshii            43.646506
, unit 2                                           HelloFresh         43.641701
1 Adelaide St E                                    Starbucks          43.650161
                                                   Touch              43.650559
1 Adelaide Street E                                Craft Beer Market  43.650159
...                                                                         ...
York Student Centre, 4700 Keele Street, Lower L... The Underground    43.774084
York U Student Centre, 4700 Keele Street, 2nd F... Mac's Sushi        43.774208
Yorkdale Shopping Center, 3401 Dufferin Street     Starbucks          43.726192
Yorkdale Shopping Centre, 3401 Dufferin Street     Mac's Sushi        43.724684
Yorkdale Shopping Mall                             Amaya Express      43.725686

                                                                      longitude  \
address                                            name
, 200 Bay Street, Unit L5                          Freshii           -79.380145
, unit 2                                           HelloFresh        -79.421299
1 Adelaide St E                                    Starbucks         -79.377797
                                                   Touch             -79.377641
1 Adelaide Street E                                Craft Beer Market -79.378093
...                                                                         ...
York Student Centre, 4700 Keele Street, Lower L... The Underground   -79.502381
York U Student Centre, 4700 Keele Street, 2nd F... Mac's Sushi       -79.498333
Yorkdale Shopping Center, 3401 Dufferin Street     Starbucks         -79.455518
Yorkdale Shopping Centre, 3401 Dufferin Street     Mac's Sushi       -79.454173
Yorkdale Shopping Mall                             Amaya Express     -79.450441

                                                                      stars_x  \
address                                            name
, 200 Bay Street, Unit L5                          Freshii                2.5
, unit 2                                           HelloFresh             2.5
1 Adelaide St E                                    Starbucks              3.5
                                                   Touch                  2.5
1 Adelaide Street E                                Craft Beer Market      3.0
...                                                                       ...
York Student Centre, 4700 Keele Street, Lower L... The Underground        2.5
York U Student Centre, 4700 Keele Street, 2nd F... Mac's Sushi            4.0
Yorkdale Shopping Center, 3401 Dufferin Street     Starbucks              4.0
Yorkdale Shopping Centre, 3401 Dufferin Street     Mac's Sushi            2.5
Yorkdale Shopping Mall                             Amaya Express          2.5

                                                                      review_count  \
address                                            name
, 200 Bay Street, Unit L5                          Freshii                     3.0
, unit 2                                           HelloFresh                  6.0
1 Adelaide St E                                    Starbucks                   6.0
                                                   Touch                      16.0
1 Adelaide Street E                                Craft Beer Market          81.0
...                                                                            ...
York Student Centre, 4700 Keele Street, Lower L... The Underground            25.0
York U Student Centre, 4700 Keele Street, 2nd F... Mac's Sushi                 7.0
Yorkdale Shopping Center, 3401 Dufferin Street     Starbucks                  12.0
Yorkdale Shopping Centre, 3401 Dufferin Street     Mac's Sushi                 5.0
Yorkdale Shopping Mall                             Amaya Express              45.0

                                                                       stars_y  \
address                                            name
, 200 Bay Street, Unit L5                          Freshii            2.333333
, unit 2                                           HelloFresh         3.000000
1 Adelaide St E                                    Starbucks          3.666667
                                                   Touch              2.687500
1 Adelaide Street E                                Craft Beer Market  3.098765
...                                                                        ...
York Student Centre, 4700 Keele Street, Lower L... The Underground    2.560000
York U Student Centre, 4700 Keele Street, 2nd F... Mac's Sushi        3.857143
Yorkdale Shopping Center, 3401 Dufferin Street     Starbucks          3.750000
Yorkdale Shopping Centre, 3401 Dufferin Street     Mac's Sushi        2.400000
Yorkdale Shopping Mall                             Amaya Express      2.266667

                                                                        useful  \
address                                            name
, 200 Bay Street, Unit L5                          Freshii            0.666667
, unit 2                                           HelloFresh         1.142857
1 Adelaide St E                                    Starbucks          1.333333
                                                   Touch              0.875000
1 Adelaide Street E                                Craft Beer Market  0.716049
...                                                                        ...
York Student Centre, 4700 Keele Street, Lower L... The Underground    0.880000
York U Student Centre, 4700 Keele Street, 2nd F... Mac's Sushi        0.428571
Yorkdale Shopping Center, 3401 Dufferin Street     Starbucks          0.583333
Yorkdale Shopping Centre, 3401 Dufferin Street     Mac's Sushi        1.600000
Yorkdale Shopping Mall                             Amaya Express      1.133333

                                                                         funny  \
address                                            name
, 200 Bay Street, Unit L5                          Freshii            0.000000
, unit 2                                           HelloFresh         0.285714
1 Adelaide St E                                    Starbucks          0.333333
                                                   Touch              0.250000
1 Adelaide Street E                                Craft Beer Market  0.123457
...                                                                        ...
York Student Centre, 4700 Keele Street, Lower L... The Underground    0.320000
York U Student Centre, 4700 Keele Street, 2nd F... Mac's Sushi        0.000000
Yorkdale Shopping Center, 3401 Dufferin Street     Starbucks          0.166667
Yorkdale Shopping Centre, 3401 Dufferin Street     Mac's Sushi        0.400000
Yorkdale Shopping Mall                             Amaya Express      0.311111

                                                                          cool
address                                            name
, 200 Bay Street, Unit L5                          Freshii            0.000000
, unit 2                                           HelloFresh         0.142857
1 Adelaide St E                                    Starbucks          0.333333
                                                   Touch              0.312500
1 Adelaide Street E                                Craft Beer Market  0.419753
...                                                                        ...
York Student Centre, 4700 Keele Street, Lower L... The Underground    0.720000
York U Student Centre, 4700 Keele Street, 2nd F... Mac's Sushi        0.142857
Yorkdale Shopping Center, 3401 Dufferin Street     Starbucks          0.166667
Yorkdale Shopping Centre, 3401 Dufferin Street     Mac's Sushi        0.800000
Yorkdale Shopping Mall                             Amaya Express      0.333333

[6795 rows x 8 columns]

In [17]:
df_yelp.loc[80, 'attributes']

'{\'RestaurantsPriceRange2\': \'2\', \'HasTV\': \'False\', \'BikeParking\': \'True\', \'OutdoorSeating\': \'False\', \'RestaurantsAttire\': "u\'casual\'", \'GoodForKids\': \'False\', \'Ambience\': "{\'romantic\': False, \'intimate\': False, \'classy\': False, \'hipster\': False, \'divey\': False, \'touristy\': False, \'trendy\': False, \'upscale\': False, \'casual\': False}", \'NoiseLevel\': "u\'quiet\'", \'RestaurantsReservations\': \'True\', \'GoodForMeal\': "{\'dessert\': False, \'latenight\': False, \'lunch\': False, \'dinner\': True, \'brunch\': False, \'breakfast\': False}", \'BusinessParking\': "{\'garage\': False, \'street\': True, \'validated\': False, \'lot\': False, \'valet\': False}", \'RestaurantsGoodForGroups\': \'True\', \'RestaurantsTableService\': \'True\', \'Alcohol\': "u\'full_bar\'"}'

In [18]:
df_yelp

,name,address,postal_code,latitude,longitude,stars_x,review_count,attributes,categories,stars_y,useful,funny,cool,text,date
0,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",3,1,0,1,Oh? Another patbingsu review? This one was bet...,2017-07-30 23:32:27
1,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",5,2,0,2,What really earns them their 5 stars is the un...,2016-01-31 16:19:16
2,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",4,0,0,0,Located inside the Galleria Supermarket.\nStop...,2016-04-29 03:43:54
3,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",5,0,0,0,Yummy cakes! U should try their sweet potato c...,2017-06-13 23:42:37
4,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",5,10,6,8,One of my favorite bakeries! This bakery is in...,2016-01-26 22:56:47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343228,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",4,1,0,2,I've been here a few times. Almost every time ...,2018-04-17 10:43:30
343229,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",3,0,0,0,I've came here for lunch several times and it ...,2017-11-17 18:12:45
343230,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",3,0,0,0,I feel mean leaving this review because servic...,2018-10-25 02:11:36
343231,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",4,0,0,0,"Decent price for lunch, after tax comes to $10...",2016-06-09 20:42:58
343232,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",5,2,0,0,I've been waiting for a new Thai restaurant in...,2017-05-24 18:40:57

In [19]:
df_yelp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 343233 entries, 0 to 343232
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   name          343233 non-null  object
 1   address       342853 non-null  object
 2   postal_code   342949 non-null  object
 3   latitude      343233 non-null  float64
 4   longitude     343233 non-null  float64
 5   stars_x       343233 non-null  float64
 6   review_count  343233 non-null  int64
 7   attributes    340466 non-null  object
 8   categories    343233 non-null  object
 9   stars_y       343233 non-null  int64
 10  useful        343233 non-null  int64
 11  funny         343233 non-null  int64
 12  cool          343233 non-null  int64
 13  text          343233 non-null  object
 14  date          343233 non-null  object
dtypes: float64(3), int64(5), object(7)
memory usage: 39.3+ MB

In [20]:
df_yelp = df_yelp[df_yelp['attributes'].notna()]

In [21]:
df_yelp.reset_index(drop = True, inplace = True)

In [22]:
local_in_review = []

for text in df_yelp['text']:
    if "local" in text:
        local_in_review.append(1)
    elif "Local" in text:
        local_in_review.append(1)
    elif "locals" in text:
        local_in_review.append(1)
    elif "Locals" in text:
        local_in_review.append(1)
    else:
        local_in_review.append(0)

In [23]:
# check length
len(local_in_review)

340466

In [24]:
df_local = pd.DataFrame({'local_in_review': local_in_review})

#check
df_local

        local_in_review
0                     0
1                     0
2                     0
3                     0
4                     0
...                 ...
340461                0
340462                0
340463                0
340464                0
340465                0

[340466 rows x 1 columns]

In [25]:
df_yelp = pd.concat([df_yelp, df_local], axis=1)

In [26]:
# check
df_yelp

,name,address,postal_code,latitude,longitude,stars_x,review_count,attributes,categories,stars_y,useful,funny,cool,text,date,local_in_review
0,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",3,1,0,1,Oh? Another patbingsu review? This one was bet...,2017-07-30 23:32:27,0
1,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",5,2,0,2,What really earns them their 5 stars is the un...,2016-01-31 16:19:16,0
2,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",4,0,0,0,Located inside the Galleria Supermarket.\nStop...,2016-04-29 03:43:54,0
3,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",5,0,0,0,Yummy cakes! U should try their sweet potato c...,2017-06-13 23:42:37,0
4,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",5,10,6,8,One of my favorite bakeries! This bakery is in...,2016-01-26 22:56:47,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340461,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",4,1,0,2,I've been here a few times. Almost every time ...,2018-04-17 10:43:30,0
340462,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",3,0,0,0,I've came here for lunch several times and it ...,2017-11-17 18:12:45,0
340463,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",3,0,0,0,I feel mean leaving this review because servic...,2018-10-25 02:11:36,0
340464,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",4,0,0,0,"Decent price for lunch, after tax comes to $10...",2016-06-09 20:42:58,0
340465,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",5,2,0,0,I've been waiting for a new Thai restaurant in...,2017-05-24 18:40:57,0

In [27]:
# check how many reviews have local in them
df_yelp['local_in_review'].value_counts()

0    332230
1      8236
Name: local_in_review, dtype: int64

In [28]:
type(df_yelp['date'][0])

str

In [29]:
# converting the date object to a datetime type
df_yelp['date'] = pd.to_datetime(df_yelp['date'], infer_datetime_format=True)

# converting the date column into year, month, day columns
df_yelp['review_year'] = df_yelp['date'].dt.year
df_yelp['review_month'] = df_yelp['date'].dt.month
df_yelp['review_day'] = df_yelp['date'].dt.day

df_yelp

,name,address,postal_code,latitude,longitude,stars_x,review_count,attributes,categories,stars_y,useful,funny,cool,text,date,local_in_review,review_year,review_month,review_day
0,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",3,1,0,1,Oh? Another patbingsu review? This one was bet...,2017-07-30 23:32:27,0,2017,7,30
1,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",5,2,0,2,What really earns them their 5 stars is the un...,2016-01-31 16:19:16,0,2016,1,31
2,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",4,0,0,0,Located inside the Galleria Supermarket.\nStop...,2016-04-29 03:43:54,0,2016,4,29
3,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",5,0,0,0,Yummy cakes! U should try their sweet potato c...,2017-06-13 23:42:37,0,2017,6,13
4,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",5,10,6,8,One of my favorite bakeries! This bakery is in...,2016-01-26 22:56:47,0,2016,1,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340461,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",4,1,0,2,I've been here a few times. Almost every time ...,2018-04-17 10:43:30,0,2018,4,17
340462,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",3,0,0,0,I've came here for lunch several times and it ...,2017-11-17 18:12:45,0,2017,11,17
340463,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",3,0,0,0,I feel mean leaving this review because servic...,2018-10-25 02:11:36,0,2018,10,25
340464,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",4,0,0,0,"Decent price for lunch, after tax comes to $10...",2016-06-09 20:42:58,0,2016,6,9
340465,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",5,2,0,0,I've been waiting for a new Thai restaurant in...,2017-05-24 18:40:57,0,2017,5,24

In [30]:
#drop the 'date' column
df_yelp.drop(['date'], axis=1, inplace=True)

In [31]:
# check if attributes remain the same for restaurants
print(df_yelp['attributes'][0])
print(df_yelp['attributes'][1])
print(df_yelp['attributes'][2])
print(df_yelp['attributes'][3])

{'RestaurantsDelivery': 'False', 'RestaurantsPriceRange2': '2', 'RestaurantsTakeOut': 'True', 'BikeParking': 'True', 'BusinessParking': "{'garage': False, 'street': False, 'validated': False, 'lot': False, 'valet': False}"}
{'RestaurantsDelivery': 'False', 'RestaurantsPriceRange2': '2', 'RestaurantsTakeOut': 'True', 'BikeParking': 'True', 'BusinessParking': "{'garage': False, 'street': False, 'validated': False, 'lot': False, 'valet': False}"}
{'RestaurantsDelivery': 'False', 'RestaurantsPriceRange2': '2', 'RestaurantsTakeOut': 'True', 'BikeParking': 'True', 'BusinessParking': "{'garage': False, 'street': False, 'validated': False, 'lot': False, 'valet': False}"}
{'RestaurantsDelivery': 'False', 'RestaurantsPriceRange2': '2', 'RestaurantsTakeOut': 'True', 'BikeParking': 'True', 'BusinessParking': "{'garage': False, 'street': False, 'validated': False, 'lot': False, 'valet': False}"}

In [32]:
# check if categories remain the same for restaurants
print(df_yelp['categories'][0])
print(df_yelp['categories'][1])
print(df_yelp['categories'][2])
print(df_yelp['categories'][3])

Bakeries, Food
Bakeries, Food
Bakeries, Food
Bakeries, Food

In [33]:
df_restaurants = df_yelp.drop(['stars_y', 'useful', 'funny', 'cool', 'text',
             'review_year', 'review_month', 'review_day'], axis=1)

df_restaurants

,name,address,postal_code,latitude,longitude,stars_x,review_count,attributes,categories,local_in_review
0,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",0
1,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",0
2,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",0
3,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",0
4,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",0
...,...,...,...,...,...,...,...,...,...,...
340461,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",0
340462,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",0
340463,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",0
340464,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",0
340465,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",0

In [34]:
#check other grouping possibilities
df_restaurants.groupby(by = ['name']).mean()

,latitude,longitude,stars_x,review_count,local_in_review
name,,,,,
'ONO Poké Bar,43.639526,-79.415855,4.0,82.000000,0.012048
00 Gelato,43.646312,-79.391329,4.5,61.000000,0.015873
0109 Dessert & Chocolate,43.814494,-79.294924,3.5,194.000000,0.010000
1 Plus 2 Pizza & Wings,43.597394,-79.520640,2.0,5.000000,0.000000
100 Percent Korean,43.825482,-79.298528,4.5,191.000000,0.010363
...,...,...,...,...,...
pico de gallo,43.654775,-79.402205,3.5,5.000000,0.000000
süüp health bar,43.659241,-79.382860,3.5,23.000000,0.043478
teashop 168,43.657685,-79.402360,3.5,5.000000,0.000000
yuan yuan Chinese Restaurant,43.791998,-79.250489,3.5,3.000000,0.000000
z-teca Gourmet Burritos,43.673038,-79.404180,2.5,34.689655,0.000000

In [35]:
df_restaurants.groupby(by = ['name', 'address', 'postal_code']).mean()

                                                                                          latitude  \
name                     address                                            postal_code
'ONO Poké Bar            100 Western Battery Road, Unit 2                   M6K 3S2      43.639526
00 Gelato                370 King Street W                                  M5V 1J9      43.646312
0109 Dessert & Chocolate 2190 McNicoll Avenue, Unit 109                     M1V 0B3      43.814494
1 Plus 2 Pizza & Wings   3206 Lakeshore Blvd. W                             M8V 1L9      43.597394
100 Percent Korean       4779 Steeles Avenue E                              M1V          43.825482
...                                                                                            ...
z-teca Gourmet Burritos  120 Bremner Boulevard, Food Court, 2nd Level       M5J 0A8      43.643090
                         327 King St W                                      M5V 1J5      43.646085
                         Commerce Court, 199 Bay St                         M5L 1E2      43.648133
                         North York Centre Food Court, 5150 Yonge Street    M2N 6L8      43.768778
                         York Lanes, York University, 4700 Keele Street,... M3J 1P3      43.778045

                                                                                         longitude  \
name                     address                                            postal_code
'ONO Poké Bar            100 Western Battery Road, Unit 2                   M6K 3S2     -79.415855
00 Gelato                370 King Street W                                  M5V 1J9     -79.391329
0109 Dessert & Chocolate 2190 McNicoll Avenue, Unit 109                     M1V 0B3     -79.294924
1 Plus 2 Pizza & Wings   3206 Lakeshore Blvd. W                             M8V 1L9     -79.520640
100 Percent Korean       4779 Steeles Avenue E                              M1V         -79.298528
...                                                                                            ...
z-teca Gourmet Burritos  120 Bremner Boulevard, Food Court, 2nd Level       M5J 0A8     -79.383072
                         327 King St W                                      M5V 1J5     -79.391092
                         Commerce Court, 199 Bay St                         M5L 1E2     -79.379509
                         North York Centre Food Court, 5150 Yonge Street    M2N 6L8     -79.413419
                         York Lanes, York University, 4700 Keele Street,... M3J 1P3     -79.495472

                                                                                         stars_x  \
name                     address                                            postal_code
'ONO Poké Bar            100 Western Battery Road, Unit 2                   M6K 3S2          4.0
00 Gelato                370 King Street W                                  M5V 1J9          4.5
0109 Dessert & Chocolate 2190 McNicoll Avenue, Unit 109                     M1V 0B3          3.5
1 Plus 2 Pizza & Wings   3206 Lakeshore Blvd. W                             M8V 1L9          2.0
100 Percent Korean       4779 Steeles Avenue E                              M1V              4.5
...                                                                                          ...
z-teca Gourmet Burritos  120 Bremner Boulevard, Food Court, 2nd Level       M5J 0A8          2.5
                         327 King St W                                      M5V 1J5          2.5
                         Commerce Court, 199 Bay St                         M5L 1E2          2.5
                         North York Centre Food Court, 5150 Yonge Street    M2N 6L8          2.5
                         York Lanes, York University, 4700 Keele Street,... M3J 1P3          2.5

                                                                                         review_count  \
name                     address                                            postal_code
'ONO Poké Bar            100 Western Battery Road, Unit 2                   M6K 3S2              82.0
00 Gelato                370 King Street W                                  M5V 1J9              61.0
0109 Dessert & Chocolate 2190 McNicoll Avenue, Unit 109                     M1V 0B3             194.0
1 Plus 2 Pizza & Wings   3206 Lakeshore Blvd. W                             M8V 1L9               5.0
100 Percent Korean       4779 Steeles Avenue E                              M1V                 191.0
...                                                                                               ...
z-teca Gourmet Burritos  120 Bremner Boulevard, Food Court, 2nd Level       M5J 0A8              10.0
                         327 King St W                                      M5V 1J5              53.0
                         Commerce Court, 199 Bay St                         M5L 1E2              28.0
                         North York Centre Food Court, 5150 Yonge Street    M2N 6L8               7.0
                         York Lanes, York University, 4700 Keele Street,... M3J 1P3              16.0

                                                                                         local_in_review
name                     address                                            postal_code
'ONO Poké Bar            100 Western Battery Road, Unit 2                   M6K 3S2             0.012048
00 Gelato                370 King Street W                                  M5V 1J9             0.015873
0109 Dessert & Chocolate 2190 McNicoll Avenue, Unit 109                     M1V 0B3             0.010000
1 Plus 2 Pizza & Wings   3206 Lakeshore Blvd. W                             M8V 1L9             0.000000
100 Percent Korean       4779 Steeles Avenue E                              M1V                 0.010363
...                                                                                                  ...
z-teca Gourmet Burritos  120 Bremner Boulevard, Food Court, 2nd Level       M5J 0A8             0.000000
                         327 King St W                                      M5V 1J5             0.000000
                         Commerce Court, 199 Bay St                         M5L 1E2             0.000000
                         North York Centre Food Court, 5150 Yonge Street    M2N 6L8             0.000000
                         York Lanes, York University, 4700 Keele Street,... M3J 1P3             0.000000

[6407 rows x 5 columns]

In [36]:
df_restaurants.groupby(by = ['name', 'address', 'postal_code', 'attributes', 'categories']).mean()

                                                                                                                                                                                                latitude  \
name                     address                                            postal_code attributes                                         categories
'ONO Poké Bar            100 Western Battery Road, Unit 2                   M6K 3S2     {'RestaurantsTakeOut': 'True', 'WiFi': "'no'", ... Poke, Asian Fusion, Hawaiian, Food, Restaurants...  43.639526
00 Gelato                370 King Street W                                  M5V 1J9     {'WiFi': "u'no'", 'BikeParking': 'True', 'Wheel... Belgian, Waffles, Restaurants, Ice Cream & Froz...  43.646312
0109 Dessert & Chocolate 2190 McNicoll Avenue, Unit 109                     M1V 0B3     {'RestaurantsGoodForGroups': 'True', 'HasTV': '... Desserts, Cafes, Food, Specialty Food, Restaura...  43.814494
1 Plus 2 Pizza & Wings   3206 Lakeshore Blvd. W                             M8V 1L9     {'RestaurantsAttire': "'casual'", 'HasTV': 'Fal... Pizza, Restaurants, Food, Chicken Wings             43.597394
100 Percent Korean       4779 Steeles Avenue E                              M1V         {'RestaurantsAttire': "u'casual'", 'Alcohol': "... Korean, Restaurants                                 43.825482
...                                                                                                                                                                                                  ...
z-teca Gourmet Burritos  120 Bremner Boulevard, Food Court, 2nd Level       M5J 0A8     {'Ambience': "{'romantic': False, 'intimate': F... Food Court, Restaurants, Fast Food, Tex-Mex, Me...  43.643090
                         327 King St W                                      M5V 1J5     {'RestaurantsPriceRange2': '1', 'RestaurantsTak... Tex-Mex, Restaurants, Mexican                       43.646085
                         Commerce Court, 199 Bay St                         M5L 1E2     {'Alcohol': "u'none'", 'OutdoorSeating': 'False... Restaurants, American (New), Fast Food, Gluten-...  43.648133
                         North York Centre Food Court, 5150 Yonge Street    M2N 6L8     {'RestaurantsTakeOut': 'True', 'HasTV': 'False'... Restaurants, Mexican, Food Court, Fast Food, Te...  43.768778
                         York Lanes, York University, 4700 Keele Street,... M3J 1P3     {'RestaurantsReservations': 'False', 'Restauran... Restaurants, Tex-Mex, Fast Food, Mexican            43.778045

                                                                                                                                                                                               longitude  \
name                     address                                            postal_code attributes                                         categories
'ONO Poké Bar            100 Western Battery Road, Unit 2                   M6K 3S2     {'RestaurantsTakeOut': 'True', 'WiFi': "'no'", ... Poke, Asian Fusion, Hawaiian, Food, Restaurants... -79.415855
00 Gelato                370 King Street W                                  M5V 1J9     {'WiFi': "u'no'", 'BikeParking': 'True', 'Wheel... Belgian, Waffles, Restaurants, Ice Cream & Froz... -79.391329
0109 Dessert & Chocolate 2190 McNicoll Avenue, Unit 109                     M1V 0B3     {'RestaurantsGoodForGroups': 'True', 'HasTV': '... Desserts, Cafes, Food, Specialty Food, Restaura... -79.294924
1 Plus 2 Pizza & Wings   3206 Lakeshore Blvd. W                             M8V 1L9     {'RestaurantsAttire': "'casual'", 'HasTV': 'Fal... Pizza, Restaurants, Food, Chicken Wings            -79.520640
100 Percent Korean       4779 Steeles Avenue E                              M1V         {'RestaurantsAttire': "u'casual'", 'Alcohol': "... Korean, Restaurants                                -79.298528
...                                                                                                                                                                                                  ...
z-teca Gourmet Burritos  120 Bremner Boulevard, Food Court, 2nd Level       M5J 0A8     {'Ambience': "{'romantic': False, 'intimate': F... Food Court, Restaurants, Fast Food, Tex-Mex, Me... -79.383072
                         327 King St W                                      M5V 1J5     {'RestaurantsPriceRange2': '1', 'RestaurantsTak... Tex-Mex, Restaurants, Mexican                      -79.391092
                         Commerce Court, 199 Bay St                         M5L 1E2     {'Alcohol': "u'none'", 'OutdoorSeating': 'False... Restaurants, American (New), Fast Food, Gluten-... -79.379509
                         North York Centre Food Court, 5150 Yonge Street    M2N 6L8     {'RestaurantsTakeOut': 'True', 'HasTV': 'False'... Restaurants, Mexican, Food Court, Fast Food, Te... -79.413419
                         York Lanes, York University, 4700 Keele Street,... M3J 1P3     {'RestaurantsReservations': 'False', 'Restauran... Restaurants, Tex-Mex, Fast Food, Mexican           -79.495472

                                                                                                                                                                                               stars_x  \
name                     address                                            postal_code attributes                                         categories
'ONO Poké Bar            100 Western Battery Road, Unit 2                   M6K 3S2     {'RestaurantsTakeOut': 'True', 'WiFi': "'no'", ... Poke, Asian Fusion, Hawaiian, Food, Restaurants...      4.0
00 Gelato                370 King Street W                                  M5V 1J9     {'WiFi': "u'no'", 'BikeParking': 'True', 'Wheel... Belgian, Waffles, Restaurants, Ice Cream & Froz...      4.5
0109 Dessert & Chocolate 2190 McNicoll Avenue, Unit 109                     M1V 0B3     {'RestaurantsGoodForGroups': 'True', 'HasTV': '... Desserts, Cafes, Food, Specialty Food, Restaura...      3.5
1 Plus 2 Pizza & Wings   3206 Lakeshore Blvd. W                             M8V 1L9     {'RestaurantsAttire': "'casual'", 'HasTV': 'Fal... Pizza, Restaurants, Food, Chicken Wings                 2.0
100 Percent Korean       4779 Steeles Avenue E                              M1V         {'RestaurantsAttire': "u'casual'", 'Alcohol': "... Korean, Restaurants                                     4.5
...                                                                                                                                                                                                ...
z-teca Gourmet Burritos  120 Bremner Boulevard, Food Court, 2nd Level       M5J 0A8     {'Ambience': "{'romantic': False, 'intimate': F... Food Court, Restaurants, Fast Food, Tex-Mex, Me...      2.5
                         327 King St W                                      M5V 1J5     {'RestaurantsPriceRange2': '1', 'RestaurantsTak... Tex-Mex, Restaurants, Mexican                           2.5
                         Commerce Court, 199 Bay St                         M5L 1E2     {'Alcohol': "u'none'", 'OutdoorSeating': 'False... Restaurants, American (New), Fast Food, Gluten-...      2.5
                         North York Centre Food Court, 5150 Yonge Street    M2N 6L8     {'RestaurantsTakeOut': 'True', 'HasTV': 'False'... Restaurants, Mexican, Food Court, Fast Food, Te...      2.5
                         York Lanes, York University, 4700 Keele Street,... M3J 1P3     {'RestaurantsReservations': 'False', 'Restauran... Restaurants, Tex-Mex, Fast Food, Mexican                2.5

                                                                                                                                                                                               review_count  \
name                     address                                            postal_code attributes                                         categories
'ONO Poké Bar            100 Western Battery Road, Unit 2                   M6K 3S2     {'RestaurantsTakeOut': 'True', 'WiFi': "'no'", ... Poke, Asian Fusion, Hawaiian, Food, Restaurants...          82.0
00 Gelato                370 King Street W                                  M5V 1J9     {'WiFi': "u'no'", 'BikeParking': 'True', 'Wheel... Belgian, Waffles, Restaurants, Ice Cream & Froz...          61.0
0109 Dessert & Chocolate 2190 McNicoll Avenue, Unit 109                     M1V 0B3     {'RestaurantsGoodForGroups': 'True', 'HasTV': '... Desserts, Cafes, Food, Specialty Food, Restaura...         194.0
1 Plus 2 Pizza & Wings   3206 Lakeshore Blvd. W                             M8V 1L9     {'RestaurantsAttire': "'casual'", 'HasTV': 'Fal... Pizza, Restaurants, Food, Chicken Wings                      5.0
100 Percent Korean       4779 Steeles Avenue E                              M1V         {'RestaurantsAttire': "u'casual'", 'Alcohol': "... Korean, Restaurants                                        191.0
...                                                                                                                                                                                                     ...
z-teca Gourmet Burritos  120 Bremner Boulevard, Food Court, 2nd Level       M5J 0A8     {'Ambience': "{'romantic': False, 'intimate': F... Food Court, Restaurants, Fast Food, Tex-Mex, Me...          10.0
                         327 King St W                                      M5V 1J5     {'RestaurantsPriceRange2': '1', 'RestaurantsTak... Tex-Mex, Restaurants, Mexican                               53.0
                         Commerce Court, 199 Bay St                         M5L 1E2     {'Alcohol': "u'none'", 'OutdoorSeating': 'False... Restaurants, American (New), Fast Food, Gluten-...          28.0
                         North York Centre Food Court, 5150 Yonge Street    M2N 6L8     {'RestaurantsTakeOut': 'True', 'HasTV': 'False'... Restaurants, Mexican, Food Court, Fast Food, Te...           7.0
                         York Lanes, York University, 4700 Keele Street,... M3J 1P3     {'RestaurantsReservations': 'False', 'Restauran... Restaurants, Tex-Mex, Fast Food, Mexican                    16.0

                                                                                                                                                                                               local_in_review
name                     address                                            postal_code attributes                                         categories
'ONO Poké Bar            100 Western Battery Road, Unit 2                   M6K 3S2     {'RestaurantsTakeOut': 'True', 'WiFi': "'no'", ... Poke, Asian Fusion, Hawaiian, Food, Restaurants...         0.012048
00 Gelato                370 King Street W                                  M5V 1J9     {'WiFi': "u'no'", 'BikeParking': 'True', 'Wheel... Belgian, Waffles, Restaurants, Ice Cream & Froz...         0.015873
0109 Dessert & Chocolate 2190 McNicoll Avenue, Unit 109                     M1V 0B3     {'RestaurantsGoodForGroups': 'True', 'HasTV': '... Desserts, Cafes, Food, Specialty Food, Restaura...         0.010000
1 Plus 2 Pizza & Wings   3206 Lakeshore Blvd. W                             M8V 1L9     {'RestaurantsAttire': "'casual'", 'HasTV': 'Fal... Pizza, Restaurants, Food, Chicken Wings                    0.000000
100 Percent Korean       4779 Steeles Avenue E                              M1V         {'RestaurantsAttire': "u'casual'", 'Alcohol': "... Korean, Restaurants                                        0.010363
...                                                                                                                                                                                                        ...
z-teca Gourmet Burritos  120 Bremner Boulevard, Food Court, 2nd Level       M5J 0A8     {'Ambience': "{'romantic': False, 'intimate': F... Food Court, Restaurants, Fast Food, Tex-Mex, Me...         0.000000
                         327 King St W                                      M5V 1J5     {'RestaurantsPriceRange2': '1', 'RestaurantsTak... Tex-Mex, Restaurants, Mexican                              0.000000
                         Commerce Court, 199 Bay St                         M5L 1E2     {'Alcohol': "u'none'", 'OutdoorSeating': 'False... Restaurants, American (New), Fast Food, Gluten-...         0.000000
                         North York Centre Food Court, 5150 Yonge Street    M2N 6L8     {'RestaurantsTakeOut': 'True', 'HasTV': 'False'... Restaurants, Mexican, Food Court, Fast Food, Te...         0.000000
                         York Lanes, York University, 4700 Keele Street,... M3J 1P3     {'RestaurantsReservations': 'False', 'Restauran... Restaurants, Tex-Mex, Fast Food, Mexican                   0.000000

[6409 rows x 5 columns]

# DO NOT RUN THE TABS BELOW

In [37]:
df_attributes = df_restaurants.loc[:, 'attributes'].apply(lambda x: pd.Series(eval(x)))

In [38]:
df_restaurants = pd.concat([df_restaurants, df_attributes], axis=1)

pd.set_option('display.max_columns', None)

df_restaurants

,name,address,postal_code,latitude,longitude,stars_x,review_count,attributes,categories,local_in_review,RestaurantsDelivery,RestaurantsPriceRange2,RestaurantsTakeOut,BikeParking,BusinessParking,WiFi,Caters,HasTV,OutdoorSeating,RestaurantsAttire,GoodForKids,Ambience,NoiseLevel,RestaurantsReservations,GoodForMeal,RestaurantsGoodForGroups,RestaurantsTableService,Alcohol,DogsAllowed,WheelchairAccessible,DriveThru,GoodForDancing,CoatCheck,Smoking,Music,BestNights,ByAppointmentOnly,HappyHour,BusinessAcceptsCreditCards,DietaryRestrictions,AcceptsInsurance,AgesAllowed,HairSpecializesIn,RestaurantsCounterService,BusinessAcceptsBitcoin
0,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food",0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340461,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN
340462,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN
340463,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN
340464,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN
340465,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai",0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
df_restaurants.drop(['attributes', 'categories'], axis = 1, inplace = True)

In [40]:
#type(df_restaurants['categories'][0])

categories = df_restaurants['categories'].apply(lambda x:x.split(', '))

categories

from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()

dummies = mlb.fit_transform(categories[:])

df_categories = pd.DataFrame(mlb.fit_transform(categories[:]), columns=mlb.classes_)

df_categories

In [41]:
#df_restaurants = pd.concat([df_restaurants, df_categories], axis=1)

In [42]:
df_restaurants

,name,address,postal_code,latitude,longitude,stars_x,review_count,local_in_review,RestaurantsDelivery,RestaurantsPriceRange2,RestaurantsTakeOut,BikeParking,BusinessParking,WiFi,Caters,HasTV,OutdoorSeating,RestaurantsAttire,GoodForKids,Ambience,NoiseLevel,RestaurantsReservations,GoodForMeal,RestaurantsGoodForGroups,RestaurantsTableService,Alcohol,DogsAllowed,WheelchairAccessible,DriveThru,GoodForDancing,CoatCheck,Smoking,Music,BestNights,ByAppointmentOnly,HappyHour,BusinessAcceptsCreditCards,DietaryRestrictions,AcceptsInsurance,AgesAllowed,HairSpecializesIn,RestaurantsCounterService,BusinessAcceptsBitcoin
0,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340461,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN
340462,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN
340463,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN
340464,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN
340465,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
branches = df_restaurants.groupby(by = ['name'])['address'].nunique().sort_values(ascending = False)

In [76]:
local = branches.loc[branches <= 2]
local_list = list(local.index)
local_list

['Milagro',
 'DaiLo',
 'Milestones Restaurants',
 'Red Lobster',
 'Green Grotto',
 'Soma Chocolatemaker',
 'Holy Chuck',
 "Church's Chicken",
 'Bazille',
 'Cacao 70',
 'Patisserie La Cigogne',
 'Salus Fresh Foods',
 'Nosso Talho',
 'Bellwoods Brewery',
 'Pizza Shab',
 'Jelly Modern Doughnuts',
 'Sushi House',
 'North Poke',
 'The Dirty Bird Chicken + Waffles',
 'DQ Grill & Chill Restaurant',
 'The Danish Pastry House',
 "Jody's Deli",
 'Soup It Up',
 'Jimmy The Greek',
 'Nutbar',
 'North of Brooklyn Pizzeria',
 'The Croissant Tree',
 'Soul Cafe',
 'Hogtown Smoke',
 "Sobey's",
 'Jules Bistro',
 "Sanagan's Meat Locker",
 'Touhenboku Ramen Restaurant',
 'Hey Lucy',
 'Touti Gelati and Cafe',
 'Paramount Lebanese Kitchen',
 'Sansotei Ramen',
 'Caffe Demetre',
 'Pour Boy',
 "Poutini's House of Poutine",
 'Euro Shawarma',
 'Deer Garden Signatures',
 "Oaks 'n Acorns",
 'Treats',
 'Delica Kitchen',
 'Kandahar Kabab',
 "Chito's Pizza",
 'AllStar Wings & Ribs',
 'De La Mer',
 'Tosto Quickfire Pizza Pasta',
 'Cafe Neon',
 'Jules Cafe Patisserie',
 'Basil Express Restaurant',
 'Jatujak',
 "Mi'hito Sushi Laboratory",
 'Tokyo Smoke',
 'Sukho Thai',
 "Ali Baba's Restaurant",
 'Hey Noodles',
 "Tori's Bakeshop",
 'Hibiscus',
 'Porchetta & Co',
 'Cafe Plenty',
 'Eggspectation',
 'Future Bakery & Cafe',
 'Souvlaki Express',
 'Bi Bim Bap',
 'Bestco Food Mart',
 'Godiva Chocolatier',
 'Pho 88',
 'The Healthy Butcher',
 'Summerhill Market',
 'Nadege',
 'Naan and Kabob',
 'Gonoe Sushi',
 'Coffee Time',
 'Indian Roti House',
 'Pho Vietnam',
 'Sunny Morning',
 'New York Fries',
 'Mymy Chicken',
 'Bobbette & Belle',
 'The One That Got Away',
 'Sunnyside Grill',
 'Boba Boy',
 'Strange Love',
 'The Meat Department',
 "Nando's",
 'Boom Breakfast & Company',
 'Sukhothai',
 'The Keg Steakhouse + Bar',
 'Sugar Loaf',
 'Sud Forno',
 'Brass Taps Pizza Pub',
 'Ichiban Sushi',
 'Congee Queen',
 'Rocky Mountain Chocolate Factory',
 'Brick Street Bakery',
 'Brick Street Bread',
 'Il Fornello',
 'Nantha Caters',
 'Strictly Bulk',
 "Nando's Flame Grilled Chicken",
 'Sultan of Samosas',
 "Yogurty's Froyo",
 'Sunrise Caribbean Restaurant',
 'Ajisen Ramen',
 'Pita Way',
 'Pita Ikram',
 'Bikkuri Japanese Restaurant',
 "Burger's Priest",
 'Grasshopper Restaurant',
 'Nomé Izakaya',
 'Pita Pit',
 'Esso',
 'Cultures',
 'Global Cheese',
 'Pizza Depot',
 'Lalibela Ethiopian Restaurant',
 'Hooked',
 'Noor Makkah',
 'Aji Sai Japanese Restaurant',
 'Banjara Indian Cuisine',
 'Loblaws Supermarkets',
 'Mos Mos',
 'Salad Days',
 'Spring China House',
 "Moxie's Grill & Bar",
 'Yogen Früz',
 'The Pie Commission',
 'Mr.Tonkatsu',
 'SU&BU',
 'Picnic',
 'Mr. Greek Express',
 'Mr. Greek',
 "Blaze Fast-Fire'd Pizza",
 'The Real Jerk',
 'AAA Bar',
 'Creeds Coffee Bar',
 'Mr Sub',
 'Crepe Delicious',
 'Little Sheep Mongolian Hot Pot',
 'Lim Ga Ne',
 'Banknote Bar',
 "Greg's Ice Cream",
 'The Big Carrot',
 'B Espresso Bar',
 'Remarkable Bean',
 'Quiznos Sub',
 "Harvey's Restaurants",
 'Gyugyuya',
 'Le Dolci',
 'FUEL+',
 "Shawarma's King",
 "Double D's",
 'King Slice',
 'Fabbrica',
 'Canyon Creek',
 'Valley Farm Produce',
 'Thai Island',
 'Fresh & Wild',
 'Queen Margherita Pizza',
 'Cherry Street Bar-B-Que',
 'Kung Fu Tea',
 'Chick-N-Joy',
 "Domino's",
 'Urban Herbivore',
 "Shopsy's Deli & Restaurants",
 'Panera Bread',
 'The 3 Brewers',
 'Amaya',
 'Bagel Stop',
 'Satay Sate',
 'Union Social Eatery',
 'Union Chicken',
 'Amato Pizza',
 'Oliver & Bonacini Café Grill',
 'H Mart',
 'Athens Pastries',
 'Ebar',
 'Happy Lemon',
 "Mac's Sushi",
 'Anoush Middle Eastern Cuisine',
 'Kothur Indian Cuisine',
 'Wallace Espresso',
 'Halibut House Fish & Chips',
 'Wakame Sushi',
 'Red Rocket Coffee',
 'Centro Pizza',
 'Hanoi 3 Seasons',
 'Lebanon Express',
 'Flock',
 'Chatime',
 'Magic Oven',
 'mmmuffins',
 'Hailed Coffee',
 'What A Bagel',
 'Ramen Isshin',
 "Ten Ren's Tea",
 'Village Pizza',
 'Maker Pizza',
 'Forget Me Not Cafe',
 'Dufflet Pastries',
 'Cheese Emporium',
 'Paintlounge',
 "Duff's Famous Wings",
 'Early Bird Coffee & Kitchen',
 'Forno Cultura',
 'Habiba',
 'Lee Chen Asian Bistro',
 'Asteria Souvlaki Place',
 "Uncle Tetsu's Japanese Cheesecake",
 "Queen's Pasta Cafe",
 'Bread & Roses Bakery Cafe',
 'Diamond Pizza',
 'Punto Gelato',
 'Wine Rack',
 'Presotea',
 'Cake House Bakery',
 'The Alley',
 'Royaltea',
 'California Sandwiches',
 'Fahrenheit Coffee',
 "Papa John's",
 'Tung Hing Bakery Company',
 'Bairrada Churrasqueira Grill',
 "Evergreen Brick Works Farmers' Market",
 "Papa John's Pizza",
 'Tutti Frutti',
 'Prohibition Gastrohouse',
 'Matsuda Japanese Cuisine',
 'Dineen Coffee',
 'Latin World',
 'Chinese Bakery',
 'Katsuya',
 'Love Chix',
 'Tsujiri',
 'Evergreen Natural Foods',
 'Wildfire Steakhouse & Wine Bar',
 "Sweet Olenka's",
 "Tropical Joe's",
 'Karahi Point',
 'Marvel Coffee Company',
 'Freshwest Grill',
 'Hamaru Sushi',
 'Goodfellas',
 'Fanzone Wings & Ribs',
 'Goodbye Gluten',
 'Good View Restaurant',
 'Grillies',
 'Falafel House',
 'Goose Island',
 "Farm'r Eatery & Catering",
 'Good Things Cafe+Juice Bar',
 'Grill Gate',
 'Grinder Coffee',
 'Goods & Provisions',
 'Golden Star',
 'Faema Canada',
 'Habitant',
 "Habeebe's Shawarma",
 'Grill Hut',
 'Grk Ygrt',
 'Grill It Up',
 'Habibi Shawarma',
 'Famous Pizza Town',
 'Gourmet Food and Wine Expo',
 'Gordo EX Cafe',
 'Hacienda las Américas',
 'Fantail Bakery-Cafe',
 'Gourmet Bakery',
 'Grinning Face Non-Dairy Gelato',
 'Gourmeats',
 'Grill Cottage',
 'Halo Brewery',
 'Good Rebel',
 'Hai Feng Chinese',
 'Hale Coffee',
 'Grilltime Gourmet Meat Shop',
 'Hakka No. 1',
 'Hakka Wow',
 'Goldie',
 'Hakka No 1 Restaurant 2',
 'Hakka Legend Asian Cuisine',
 'Grillway Souvlaki House On Bloor',
 'Goldstone Noodle Restaurant',
 'Goldstruck Coffee',
 'Golden Wheat Bakery & Pastry',
 'Golden Thai Restaurant',
 'Faith Culture',
 'Halal Meals',
 'Hakka Happy',
 'Farm Fresh Mart',
 'Golden Wok Chinese Restaurant',
 'Hakka Garden Chinese Restaurant',
 'Farm Boy',
 'Gong Cha Tea',
 'Hakka Cottage',
 'Grey Tiger',
 'Hakata Shoryuken',
 'Good Bite Restaurant',
 'Hair of the Dog',
 'FBI PIZZA',
 'Good Cheese',
 'Good Day Good Time Tea',
 'Grillway Subs & Burgers',
 'Fahmee Bakery & Jamaican Foods',
 'Haida Sandwich',
 'Famoso Neapolitan',
 'Green Mango Express',
 'Gouter',
 'Govardhan Thal',
 'Green Beanery',
 'Gusto 101',
 'Green Basil Restaurant',
 'Green Pepper',
 'Greek Olives',
 'Falafel World',
 'Face To Face Games',
 'Greek In The Village',
 'Gusto Pizza',
 'Green Post',
 'Greek & Co',
 'Greece Restaurant',
 'Guu Izakaya Toronto',
 'Green Room',
 'Gyro Bar!',
 'Great Food Supermarket',
 'Gyro Bar! Souvlaki Kitchen',
 'Factory Girl',
 'Gushi Japanese Street Food',
 'Green Beanery Warehouse Outlet',
 'Green Onion Pan Asian Cuisine',
 'Green Mango Boys',
 'Green Lady',
 'Green Grotto Tea Room',
 'Green Natural Health Foods',
 'Falafel Royal',
 'Green Garden Bubble Tea Shop',
 'Green Eggplant Restaurant',
 'Gud to Go',
 'Guschlbauer',
 'Guest House Chinese',
 'Green Papaya',
 'Green Earth Vegetarian Cuisine',
 'Green Earth Organics',
 'Guirei Japanese Restaurant',
 'Green Curry',
 'Green Box Express',
 'Green Thumb Fruit Market',
 'Gyu-Kaku Japanese BBQ',
 'Ground Level Cafe',
 'Graceful Vegetarian Restaurant',
 'Granite Brewery & Restaurant',
 'Granite Bistro',
 'Grey Gardens',
 'Grandeur Palace',
 'Family Shawarma & Falafel',
 'Grand Electric',
 'HCafe Japanese Cafe',
 "Grace O'Malley's",
 'Family Bakery Cafe',
 'HK Garden',
 "Gryfe's Bagel Bakery",
 'Ha Gow Dim Sum House',
 'Grabba Pizza',
 "Govinda's",
 'FIKA',
 'Falafel Hut Village',
 "Greta Solomon's",
 'Grano Restaurant',
 'Faley Restaurant',
 'Greens Vegetarian Restaurant',
 'GroceryMarket.ca',
 'Fair Grounds Organic Café & Roastery',
 'Gyubee Japanese BBQ - Downtown',
 'Greenfield Market',
 'Great China Herbs Centre',
 'Great Burger Kitchen',
 'Grazie Ristorante',
 'Famiglia Baldassarre',
 'Grappa Restaurant',
 'Greenwood Smokehouse BBQ',
 'Fabarnak Community Cafe and Catering',
 'Faema Caffe',
 'Grenadier Cafe',
 'FORTY2 Supperclub',
 'FK',
 'H Bar',
 'Grace Meats & Fine Foods',
 'Feng Cha',
 'Golden Rice Noodle',
 "Gabby's Bar and Grill",
 'FuZen',
 'Fu Lai',
 'Ftrip',
 "Fish'D By EDO",
 'Fruity Mix',
 'Fruits Market',
 'Fruitful Market',
 'Fruit King',
 'Froshberg Gelato',
 'Front Street Foods',
 'Frog and the Crown',
 'Fritou',
 'Friendly Greek',
 'Fishman Lobster Clubhouse Restaurant',
 'Freta Enjera',
 'Freshwood Grill',
 'Fit For Life Sandwich Bar',
 'Freshco',
 'FreshEast',
 'Fresh on Spadina',
 'Fresh on Eglinton',
 'Fresh on Crawford',
 'Fresh Rolls',
 'Fresh Pizza Plus',
 'Fresh On Bloor',
 'Fit for Life',
 'Fresh Off The Boat',
 'Fubar',
 'Fudao noodle house',
 'Fugo Desserts',
 'Fushimi',
 'GB Hand-pulled Noodles',
 'Fiorentina',
 "G's Fine Foods",
 "Fynn's of Temple Bar",
 'Firkin Freehouse',
 'Firkin On Danforth',
 'Fv Foods',
 'Fuwa Fuwa Japanese Pancakes',
 'Future Bistro',
 'Futura Granita + Gelato',
 'Fusilli Restaurant',
 'Fusia Asian Kitchen',
 "Fusaro's Kitchen",
 'First and Last',
 "Fusaro's",
 'Furama Dim Sum & Bakery',
 'Furama Cake and Desserts Garden',
 'Furama Cake & Dessert Garden',
 'Firkin On Yonge',
 'Funnel Cake Express',
 'Fune Japanese Restaurant',
 'Full of Beans Coffee House & Roastery',
 'Full Stop',
 'First Choice Restaurant',
 'Full House Desserts',
 'Fukui Sushi',
 'Fresh Cup Bubble Tea',
 'Five Doors North',
 'Fresh City Farms',
 'Food Palace Gelato',
 'Flip Toss & Thai Kitchen',
 'For The Win Board Game Cafe & Bar',
 'For The Love of Cake Custom Creations',
 'Foody World',
 'Foodwares Market',
 "Flo's Diner",
 'Foods For Life',
 "Foodoe's  Fish and Chips",
 'Foodland',
 'Foodbenders',
 'Food Studio Cafe',
 'Food Plus Market',
 'Food Kingdom',
 'Fleur Du Jour',
 'Food Dudes Pantry',
 'Flor de Sal',
 'Florentia',
 'Food Depot',
 'Flying Pony',
 'Food & Liquor',
 'Fong On Foods',
 'Fonda Lola',
 'Folly Brewing',
 'Folia Grill',
 'Foggy Dew Irish Pub',
 'Focaccia Italian Sandwiches',
 'Formocha',
 'Fort York Pizzeria',
 'Fresh City',
 'Fix Coffee + Bikes',
 'Fresh Choice Cafe',
 'Fresh Burger',
 "Fresco's Fish & Chips",
 'Fresca Pizza & Pasta',
 'French Quarters',
 'French Made',
 'Free Times Cafe',
 "Freddie's No Frills",
 'Five Points Hot Chicken',
 "Fred's Not Here",
 'Frascati',
 "Frankie's",
 "Frank's Pizza House Restaurant",
 'Fortune House Restaurant',
 'Francobollo',
 'Flaky Tart',
 'Francesca Italian Bakery & Delicatessen',
 'Foxley Bistro and Bar',
 'Flame Shack',
 'Flaming Kitchen',
 'Fox and Fiddle Yorkmills',
 'Fox & Fiddle',
 'Founder Bar',
 'Flaming Stove',
 'Flavor Cuisine',
 'Fossil & Haggis Pub',
 'GIG@bites Internet Cafe',
 "Gabby's Bistro",
 'Golden Ray Chinese Restaurant',
 'Fine Wine Reserve',
 'Glory Of India Roti Cuisine',
 'Glory Hole Doughnuts',
 'Gloria Espresso Bar & Cafe',
 'Globe Bistro',
 'Global Imperial Cuisine',
 'Gladstone Hotel',
 "Fat Louie's BBQ",
 'Fat Ninja Bite',
 'Fat Pasha',
 'Glad Day Bookshop',
 'Giulietta',
 "Gio Rana's Really Really Nice Restaurant",
 "Gino's Pizza & Wing Machine",
 'Fearless Meat',
 'Feast of Dilli',
 'Focaccia Restaurant',
 'Gingerman Restaurant',
 'Fennel Eatery',
 'Ginger Restaurant',
 'Fermentations',
 'Ginger And Onion Cuisine',
 "Fernando's Hideaway",
 'Gin Mill',
 'Gilaneh Restaurant',
 'Gigabites',
 'Ghazale Restaurant',
 'Ferraro 502',
 'Glow Fresh Grill',
 'Fat Bastard Burrito Co',
 'Go For Tea',
 'Golden Bubbles',
 'Farmacia Health Bar',
 'Golden Pizza',
 'Golden Patty',
 'Golden Joy Hakka Restaurant',
 'Golden House',
 'Golden Gecko Coffee',
 'Golden Gate restaurant',
 'Farmhouse Tavern',
 'Golden Dumpling',
 'Farside',
 'Golden Diner Family Restaurant',
 'Golden Cook Caribbean Restaurant',
 'Golden Asian Cuisine',
 'Go Go China',
 'Gold Standard',
 'Gold Bowl Asian Noodle Soup',
 'Gol Take-Out',
 'Gohyang Restaurant',
 'Gogi Bap',
 'Faryab Kabab',
 'Godspeed Brewery',
 'Godiva',
 'Gobo Sushi',
 'Goat Coffee Co',
 'Go Tours Canada',
 'Go Topoki',
 'Ghareeb Nawaz',
 'Get & Go Burrito',
 "Gerry's Fast Foods",
 'Galata Cafe',
 'Ganto Sushi',
 'Gangnam Sushi Restaurant',
 'Gandhi Cuisine',
 'Gamberoni Restaurant',
 'Galo Do Sardinha Churrasqeira',
 'Gallery Sushi',
 'Hamish Kitchen Restaurant',
 "Gale's Snack Bar",
 'Galaxy T&T',
 'Figs Breakfast & Lunch',
 'Figures',
 'Galaxy Fresh Foods',
 'Film Cafe by Eative',
 'Figo',
 'Gaia Natural Foods',
 "Gabby's on The Danforth",
 "Gabby's at the Isabella Hotel",
 "Gabby's Roncesvalles",
 "Gabby's RoadHouse",
 'Filosophy Pastry and Espresso Bar',
 "Gabby's Kingston Road",
 "Gabby's Junction",
 "Gabby's Grill and Taps",
 "Gabby's Grill and Bar",
 "Gabby's Food and Fuel",
 "Gabby's Eatery and Taps",
 'Garden Gangsters',
 'Garden Gate Restaurant',
 'Ferro Bar & Cafe',
 "Gayley's Cafe",
 'Festival Fine Foods',
 'Gerrard Pizza',
 'Georgia Restaurant',
 "George's Pizza and Panzerotto",
 "George's Deli & BBQ",
 "George's BBQ Chicken",
 'George',
 'Genji Sushi',
 'General Assembly Pizza',
 'Gelato Simply Italian',
 'Gdous',
 'Gazi Mezebar',
 'Feta & Olives',
 "Garden's Food",
 'Feta and Olives',
 "Fiddler's Dell Bar & Grill",
 'Gautama',
 'Garleek Kitchen',
 "Fidel Gastro's",
 'Field Trip Cafe',
 "Gare De L'est",
 'Gardenview Convenience',
 'Fieramosca',
 'Fiesta Burrito',
 'Fiesta Farms',
 'Fifth Pubhouse',
 'Hamdi Restaurant',
 'Hina Sushi',
 'Han Ba Tang',
 'Keele Ur Hunger',
 'Kibo Summerhill',
 'Kibo Sushi',
 'Kibo Sushi House, Liberty village',
 'Kid Lee',
 'Kiin',
 'Kiku Japanese Cuisine',
 'Kim Bo Vietnamese & Thai Restaurant',
 'Kim Natural Food',
 'Kim Vietnamese Restaurant',
 'Kimama',
 'Kimchi House',
 'Kimchi Korea House',
 'Kimono Japanese Grill & Sushi',
 'Kin Kin Bakery & Bubble Tea',
 'Kin Kin Bubble Tea',
 'Ki Modern Japanese + Bar',
 'Khorak Supermarket',
 'Khmer Thai Restaurant',
 'Kensington Market',
 'Kekou Gelato',
 'Kekou Gelato House',
 'Kellys Landing',
 "Ken Ho's Snack Service",
 'Kensington Brewing Company',
 'Kensington Cafe',
 'Kensington Natural Bakery',
 'Khau Gully',
 'Kenzo',
 'Kenzo Ramen Bloor',
 'Kernels Popcorn',
 "Kevin's Taiyaki",
 'Khao Gaeng',
 'Khao San Road',
 'Kin-Kin Bakery & Bubble Tea',
 'Kin-Kin Bakery and Bubble Tea',
 "King George's Arms",
 'Kitchen Table',
 'Kiro Sushi',
 'Kit Kat Italian Bar & Grill',
 'Kitchen',
 'Kitchen Empire',
 'Kitchen King Jerk',
 'Kitchen On Sixth',
 'Kitchen Table Grocery Stores',
 'Kintako Japanese Restaurant',
 'Kitson & Co Sandwiches',
 'Kitten and the Bear',
 "Kiva's  Bagel Bar",
 "Kiva's Bagel Bar",
 'Kiyo',
 'Kiza Restaurant & Lounge Toronto',
 'Kintaro Izakaya',
 'Kingyo',
 'King Palace',
 "King's Diner",
 'King Place',
 'King Rustic',
 'King Solomon and Queen of Sheba',
 'King Street Social Kitchen',
 'King Taps',
 "King's Café",
 "King's Noodle Restaurant",
 'Kingsway Meat Products & Deli',
 "King's Tacos",
 "King's Vegetarian Food",
 'Kings Delight',
 'Kings Delight Caribbean Cuisine',
 "Kings' Deli Cafe",
 'Kingston Chinese Restaurant',
 'Kefi',
 'Kebaberie Yorkville',
 'Knuckle Sandwich',
 'Kebab 49',
 'Just Soups Take Out & Catering',
 "Jz's Pizza",
 'K-Wok',
 'KABOOM Chicken',
 'KIBO Sushi & Tapas',
 'KINKA IZAKAYA BLOOR',
 'KINKA IZAKAYA NORTH  YORK',
 'KINKA IZAKAYA ORIGINAL',
 'KOKO! Share Bar',
 'KOS Cafe and Restaurant',
 'KOS Restaurant',
 'KaKa All You Can Eat',
 'Kabab & Tikah House',
 'Kabalen',
 'Kabul Express',
 'Junction Local',
 'Junction Fromagerie',
 'Junction Craft Brewing',
 'Juice & Java',
 "Joso's",
 'Joy Thai Restaurant',
 'Joy of Harvest',
 'Joyous Thai',
 'Jugemu',
 'Jugo Juice FCP',
 'Juice & Java Cafe',
 "Jun's Kitchen",
 'Juice Box',
 'Juice Rush',
 "Julie's Cuban Restaurant",
 'Jumbo Burger',
 'Jumbo Empanadas',
 'Jump Restaurant',
 'Kabul Kabab House',
 'Kabul Restaurant and Bakery',
 'Kaga By Ginza',
 'Katana on Bay',
 'Karizma',
 'Karma Food Co-operative',
 "Karma's Kitchen",
 'Kasa Moto',
 'Kasai Grill House',
 'Kasturi Restaurant & Banquet Hall',
 'Kathmandu Restaurant',
 'Karbouzi',
 "Kathy's Corner",
 'Katsu Japanese Restaurant',
 'Kawa Sushi',
 'Kay Pacha',
 'Kayagum',
 'Keating Channel Pub & Grill',
 "Karine's",
 'Karaikudi',
 'Kaikaki Japanese Restaurant',
 'Kamasutra Indian Restaurant & Wine Bar',
 'Kailash Parbat',
 'Kairali - Taste of Kerala',
 'Kaiseki Yu-zen Hashimoto',
 'Kalendar',
 'Kalesa Restobar',
 'Kalyvia On the Danforth',
 'Kami Sushi',
 'Kapit Bahay Filipino Restaurant',
 'Kanda Izakaya',
 'Kanga',
 'Kanga Aussie Meat Pies',
 'Kanga Pies',
 'Kanpai Snack Bar',
 'Kanto by Tita Flips',
 'Kniblets Cafe',
 "Ko'ox Hana",
 'Han Shi Fang',
 'La Bella Managua',
 'La Paloma Gelateria & Cafe',
 'La Pupusa Loka',
 'La Rev',
 'La Risata Ristorante',
 'La Rose Bakery',
 'La Sala Restaurant',
 'La Salumeria',
 'La Sani Grill',
 'La Societe - Toronto',
 'La Vecchia Ristorante',
 'La Veranda Osteria',
 'La Vinia',
 'LaPaz Batchoy Toronto',
 'Lab Sense',
 'Labothéry',
 'La Palma',
 'La Palette',
 "La Mona's",
 'La Famiglia',
 'La Boheme',
 'La Boucherie Fine Meats',
 'La Brasserie',
 'La Bruschetta Restaurant',
 'La Chilaca Taqueria',
 'La Cocina De Dona Luz',
 'La Fenice',
 'La Luce Ristorante',
 'La Forchetta',
 'La Fromagerie',
 'La Guanaquita',
 'La Hacienda Restaurant',
 'La Libre',
 'La Limonada',
 'Lac Vien Vietnamese Restaurant',
 'Ladurée Boutique and Tea Salon',
 'Lageez',
 'Le Baratin',
 'Lavazza Espression',
 'Lavazza Espression Cafe',
 "Lawai'a Poke Bar",
 'Laylow Brewery',
 'Laziza',
 "Lazy Daisy's Cafe",
 'Le Cafe Michi',
 'Latin Taste',
 'Le Gourmand',
 'Le Greeka',
 'Le Montmartre French Restaurant',
 'Le Notre Bistro',
 'Le Papillon On Front',
 'Le Paradis Brasserie Bistro',
 'Laura Secord',
 'Latazza Cafe',
 'Lahore Chaat and Paan House',
 'Lambretta Pizzeria East',
 'Lahore Grill & Fast Food',
 'Lahore Paan Center',
 'Lahore Tikka House',
 'Lai Wah Heen',
 'Lake Inez',
 'Lambretta Pizzeria & Wine Bar',
 'Lamesa Filipino Kitchen',
 'Lasa by Lamesa',
 'Lan Restaurant',
 'Lan Sushi',
 'Landing Noodles',
 'Lao Fu Zhou',
 'Lao Thai Restaurant',
 "Lara's Restaurant",
 'La Bettola di Terroni',
 'La Barista Café',
 'KoJa Restaurant',
 'La Bamboche',
 'Kostas Greek Bakery',
 'Kotta',
 'Kottu Kadai',
 'Kovalsky Restaurant',
 'Kowloon Dim Sum Restaurant',
 'Koya Japan',
 'Koyoi Restaurant & Bar',
 "Kozlik's Canadian Mustard",
 "Kramer's Bar & Grill",
 'Krave Coffee',
 'Krazy Roll',
 'Krepesz Cafe & Bar',
 'Krispy Kreme',
 'Krispy Kreme Cafe',
 "Krispy Kreme's Doughnut Cafe",
 'Kost',
 'Koryo Korean Restaurant & Bar',
 'Kornerstones',
 'Kokyo Japanese Restaurant',
 'Kobi Korean Restaurant',
 'Koffea Espresso Bar',
 'Koha Pacific Kitchen',
 'Kohinoor Foods',
 'Koi Koi Saké Bar',
 'Koji Japanese Restaurant',
 'Kong Kee Barbeque',
 'Koricancha Restaurant',
 'Konjiki Ramen',
 'Konner Chinese Restaurant',
 'Kookminhakgyo',
 'Korea House',
 'Korean Restaurant OUR',
 'Korean Village Restaurant',
 'Kristapsons',
 'Kristapsons - On Yonge',
 'Kroran Uyghur Cuisine',
 'LCBO - Gerrard and Pape',
 'LCBO - Bloor West Village',
 'LCBO - Cabbagetown',
 'LCBO - Chinatown',
 'LCBO - Danforth and Greenwood',
 'LCBO - Dundas and Dovercourt',
 'LCBO - Eglinton and Avenue',
 'LCBO - Maple Leaf Gardens',
 "L'Unita",
 'LCBO - Queen and Coxwell',
 'LCBO - St. Lawrence Market',
 'LCBO - Yonge Eglinton Centre',
 'LCBO Maple Leaf Square',
 'LHL Seafood Restaurant',
 'LOT 41',
 "L'espresso Bar Mercurio",
 'Kū-kŭm',
 'Krystos Modern Greek Cuisine',
 'Kurtis Coffee',
 'Kub Khao Thai Eatery',
 'Kumo Japanese Restaurant',
 "Kunafa's",
 'Kung Fu Duck',
 'Kuni Sushi Ya',
 'Kupfert & Kim - Metro Hall',
 'Kushimaru',
 'Kōjin',
 "Kuya Willie's Kainan",
 'Kwan',
 'Kwan At York Mills',
 'Kwan Dim Sum Express',
 'Kyoto House Japanese Restaurant',
 'Kyouka Ramen',
 'Jollibee',
 "Johnny's Shawarma",
 "Johnny's Hamburgers",
 'Hero Certified Burgers - Yonge & St. Clair',
 'Hogtown Smoke In the Beach',
 'Hogtown Vegan',
 'Hoki Poke',
 'Hokkaido Ramen Santouka',
 'Hokkaido Sushi',
 'Hollandaise Diner',
 'Hollywood Cone',
 'Hollywood Gelato',
 'Holt Renfrew',
 'Holy Chicken',
 'Holy Snack',
 'Home',
 'Home Feel Seafood Chinese Restaurant',

In [77]:
df_locals = df_restaurants[df_restaurants['name'].isin(local_list)]

df_locals

,name,address,postal_code,latitude,longitude,stars_x,review_count,local_in_review,RestaurantsDelivery,RestaurantsPriceRange2,RestaurantsTakeOut,BikeParking,BusinessParking,WiFi,Caters,HasTV,OutdoorSeating,RestaurantsAttire,GoodForKids,Ambience,NoiseLevel,RestaurantsReservations,GoodForMeal,RestaurantsGoodForGroups,RestaurantsTableService,Alcohol,DogsAllowed,WheelchairAccessible,DriveThru,GoodForDancing,CoatCheck,Smoking,Music,BestNights,ByAppointmentOnly,HappyHour,BusinessAcceptsCreditCards,DietaryRestrictions,AcceptsInsurance,AgesAllowed,HairSpecializesIn,RestaurantsCounterService,BusinessAcceptsBitcoin
0,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340461,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN
340462,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN
340463,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN
340464,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN
340465,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
df_locals.to_csv('local_restaurants.csv', index = False)

In [78]:
df_test = pd.read_csv('local_restaurants.csv')

C:\Users\Aref\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (9,37,38,39,40,41,42) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [79]:
df_test

,name,address,postal_code,latitude,longitude,stars_x,review_count,local_in_review,RestaurantsDelivery,RestaurantsPriceRange2,RestaurantsTakeOut,BikeParking,BusinessParking,WiFi,Caters,HasTV,OutdoorSeating,RestaurantsAttire,GoodForKids,Ambience,NoiseLevel,RestaurantsReservations,GoodForMeal,RestaurantsGoodForGroups,RestaurantsTableService,Alcohol,DogsAllowed,WheelchairAccessible,DriveThru,GoodForDancing,CoatCheck,Smoking,Music,BestNights,ByAppointmentOnly,HappyHour,BusinessAcceptsCreditCards,DietaryRestrictions,AcceptsInsurance,AgesAllowed,HairSpecializesIn,RestaurantsCounterService,BusinessAcceptsBitcoin
0,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bakery Gateau,"865 York Mills Road, Unit 1",M3B 1Y6,43.754093,-79.349548,4.5,8,0,False,2,True,True,"{'garage': False, 'street': False, 'validated'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296934,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN
296935,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN
296936,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN
296937,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN
296938,Thai Fantasy,578 Yonge Street,M4Y 1Z3,43.665120,-79.384809,4.0,113,0,True,2,True,True,"{'garage': False, 'street': True, 'validated':...",u'free',True,False,False,u'casual',True,"{'touristy': False, 'hipster': False, 'romanti...",'average',True,"{'dessert': False, 'latenight': False, 'lunch'...",True,True,u'beer_and_wine',NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN